# Generated by Django 4.2 on 2024-11-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
