# Generated by Django 4.2 on 2024-10-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstlevelcategory',
            options={'verbose_name_plural': 'First Level Categories'},
        ),
        migrations.AlterModelOptions(
            name='secondlevelcategory',
            options={'verbose_name_plural': 'Second Level Categories'},
        ),
        migrations.AlterModelOptions(
            name='thirdlevelcategory',
            options={'verbose_name_plural': 'Third Level Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='first_level_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.firstlevelcategory'),
        ),
    ]
