# Generated by Django 4.2 on 2024-10-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_firstlevelcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
